import sys
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text
import jieba
from collections import Counter
import re
from typing import List, Dict, Tuple, Optional
import warnings
warnings.filterwarnings('ignore')

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))


def load_clustered_data(clusters_path: str = 'data/processed/kmeans_clusters.csv') -> pd.DataFrame:
    """Load the clustered data generated by kmeans_cluster.py."""
    if not Path(clusters_path).exists():
        raise FileNotFoundError(f"Clustered data not found at {clusters_path}. Run kmeans_cluster.py first.")

    print(f"Loading clustered data from {clusters_path}")
    df = pd.read_csv(clusters_path)
    print(f"Loaded {len(df)} products with {df['cluster'].nunique()} clusters")
    return df


def prepare_cluster_texts(df: pd.DataFrame, text_columns: Optional[List[str]] = None) -> Dict[int, List[str]]:
    """
    Prepare text data for each cluster.

    Args:
        df: DataFrame with clustered data
        text_columns: List of column names to use for text extraction

    Returns:
        Dictionary mapping cluster_id to list of text documents
    """
    if text_columns is None:
        # Default text columns - use available cleaned text or original text
        text_columns = []
        if 'embedding_text' in df.columns:
            text_columns = ['embedding_text']
        else:
            # Try cleaned columns first, then original
            potential_columns = [
                'name_zh_clean', 'name_en_clean',
                'description_zh_clean', 'description_en_clean',
                'name_zh', 'name_en',
                'description_zh', 'description_en'
            ]
            text_columns = [col for col in potential_columns if col in df.columns]

        if not text_columns:
            raise ValueError("No suitable text columns found in the data")

    print(f"Using text columns: {text_columns}")

    cluster_texts = {}

    for cluster_id in sorted(df['cluster'].unique()):
        cluster_df = df[df['cluster'] == cluster_id]
        texts = []

        for _, row in cluster_df.iterrows():
            # Combine text from selected columns
            combined_text = []
            for col in text_columns:
                if col in row and pd.notna(row[col]):
                    combined_text.append(str(row[col]))

            if combined_text:
                texts.append(' '.join(combined_text))

        cluster_texts[cluster_id] = texts
        print(f"Cluster {cluster_id}: {len(texts)} documents")

    return cluster_texts


def extract_chinese_terms(text: str) -> List[str]:
    """Extract Chinese terms using jieba."""
    # Remove non-Chinese characters but keep spaces
    text = re.sub(r'[^\u4e00-\u9fff\s]', '', text)
    # Tokenize with jieba
    terms = jieba.cut(text)
    return [term for term in terms if len(term.strip()) > 1]


def extract_english_terms(text: str) -> List[str]:
    """Extract English terms."""
    # Keep only English letters, numbers, and spaces
    text = re.sub(r'[^a-zA-Z\s]', '', text.lower())
    # Split into words
    terms = text.split()
    return [term for term in terms if len(term) > 2]  # Filter short words


def get_top_tfidf_terms(cluster_texts: Dict[int, List[str]],
                       max_features: int = 1000,
                       top_n: int = 10,
                       ngram_range: Tuple[int, int] = (1, 2),
                       language: str = 'mixed') -> Dict[int, List[Tuple[str, float]]]:
    """
    Extract top TF-IDF terms for each cluster.

    Args:
        cluster_texts: Dictionary mapping cluster_id to list of texts
        max_features: Maximum number of features for TF-IDF
        top_n: Number of top terms to return per cluster
        ngram_range: N-gram range for vectorization
        language: 'mixed', 'chinese', or 'english'

    Returns:
        Dictionary mapping cluster_id to list of (term, score) tuples
    """
    cluster_top_terms = {}

    # Prepare custom stop words
    stop_words = list(text.ENGLISH_STOP_WORDS)
    # Add common Chinese stop words
    chinese_stop_words = ['的', '了', '和', '是', '就', '都', '而', '及', '與', '著', '或', '一個', '沒有', '我們', '你們', '他們', '這', '那', '那個']
    stop_words.extend(chinese_stop_words)

    for cluster_id, texts in cluster_texts.items():
        if not texts:
            cluster_top_terms[cluster_id] = []
            continue

        print(f"Processing cluster {cluster_id} with {len(texts)} documents")

        # Choose tokenizer based on language
        if language == 'chinese':
            tokenizer = extract_chinese_terms
        elif language == 'english':
            tokenizer = extract_english_terms
        else:  # mixed
            def mixed_tokenizer(text):
                zh_terms = extract_chinese_terms(text)
                en_terms = extract_english_terms(text)
                return zh_terms + en_terms
            tokenizer = mixed_tokenizer

        # Create TF-IDF vectorizer
        vectorizer = TfidfVectorizer(
            max_features=max_features,
            stop_words=stop_words,
            ngram_range=ngram_range,
            tokenizer=tokenizer,
            token_pattern=None,  # Disable default token pattern when using tokenizer
            lowercase=False if language == 'chinese' else True
        )

        try:
            # Fit and transform
            tfidf_matrix = vectorizer.fit_transform(texts)

            # Get feature names
            feature_names = vectorizer.get_feature_names_out()

            # Calculate mean TF-IDF scores across all documents in cluster
            mean_tfidf = np.array(tfidf_matrix.mean(axis=0)).flatten()

            # Get top terms
            top_indices = mean_tfidf.argsort()[-top_n:][::-1]
            top_terms = [(feature_names[i], mean_tfidf[i]) for i in top_indices]

            cluster_top_terms[cluster_id] = top_terms

        except Exception as e:
            print(f"Warning: Could not process cluster {cluster_id}: {e}")
            cluster_top_terms[cluster_id] = []

    return cluster_top_terms


def generate_cluster_labels(cluster_top_terms: Dict[int, List[Tuple[str, float]]],
                          min_terms: int = 2,
                          max_terms: int = 4,
                          score_threshold: float = 0.1) -> Dict[int, str]:
    """
    Generate descriptive labels for clusters based on top TF-IDF terms.

    Args:
        cluster_top_terms: Dictionary from get_top_tfidf_terms
        min_terms: Minimum number of terms to include in label
        max_terms: Maximum number of terms to include in label
        score_threshold: Minimum TF-IDF score threshold

    Returns:
        Dictionary mapping cluster_id to generated label
    """
    cluster_labels = {}

    for cluster_id, terms in cluster_top_terms.items():
        if not terms:
            cluster_labels[cluster_id] = f"Cluster {cluster_id}"
            continue

        # Filter terms by score threshold
        filtered_terms = [(term, score) for term, score in terms if score >= score_threshold]

        if len(filtered_terms) < min_terms:
            # Use all available terms if filtering is too aggressive
            filtered_terms = terms[:max_terms]

        # Select top terms
        selected_terms = filtered_terms[:max_terms]

        if not selected_terms:
            cluster_labels[cluster_id] = f"Cluster {cluster_id}"
        else:
            # Create label by joining terms
            label_terms = [term for term, _ in selected_terms]
            label = ' '.join(label_terms)
            cluster_labels[cluster_id] = label.title()

    return cluster_labels


def label_clusters(
    clusters_path: str = 'data/processed/kmeans_clusters.csv',
    output_path: str = 'data/processed/clusters_labeled.csv',
    text_columns: List[str] = None,
    top_n_terms: int = 10,
    label_max_terms: int = 4,
    language: str = 'mixed',
    **kwargs
) -> Tuple[pd.DataFrame, Dict[int, str]]:
    """
    Complete pipeline to label clusters using TF-IDF.

    Args:
        clusters_path: Path to clustered data CSV
        output_path: Path to save labeled data
        text_columns: Text columns to use for TF-IDF
        top_n_terms: Number of top TF-IDF terms to extract per cluster
        label_max_terms: Maximum terms to include in cluster labels
        language: Language setting ('mixed', 'chinese', 'english')
        **kwargs: Additional parameters for TF-IDF

    Returns:
        Tuple of (labeled_dataframe, cluster_labels_dict)
    """
    # Load data
    df = load_clustered_data(clusters_path)

    # Prepare cluster texts
    cluster_texts = prepare_cluster_texts(df, text_columns)

    # Extract top TF-IDF terms
    cluster_top_terms = get_top_tfidf_terms(
        cluster_texts,
        top_n=top_n_terms,
        language=language,
        **kwargs
    )

    # Generate labels
    cluster_labels = generate_cluster_labels(
        cluster_top_terms,
        max_terms=label_max_terms
    )

    # Add labels to dataframe
    df_labeled = df.copy()
    df_labeled['cluster_label'] = df_labeled['cluster'].map(cluster_labels)

    # Save results
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    df_labeled.to_csv(output_path, index=False)
    print(f"Saved labeled clusters to {output_path}")

    # Print results
    print("\nCluster Labels:")
    print("-" * 50)
    for cluster_id in sorted(cluster_labels.keys()):
        print(f"Cluster {cluster_id}: {cluster_labels[cluster_id]}")

    # Save cluster labels separately
    labels_df = pd.DataFrame({
        'cluster': list(cluster_labels.keys()),
        'label': list(cluster_labels.values())
    })
    labels_path = str(Path(output_path).parent / 'cluster_labels.csv')
    labels_df.to_csv(labels_path, index=False)
    print(f"Saved cluster labels summary to {labels_path}")

    return df_labeled, cluster_labels


def analyze_cluster_quality(df_labeled: pd.DataFrame) -> Dict[str, any]:
    """Analyze the quality and characteristics of cluster labels."""
    analysis = {}

    # Label length statistics
    label_lengths = df_labeled['cluster_label'].str.split().str.len()
    analysis['label_stats'] = {
        'mean_length': label_lengths.mean(),
        'min_length': label_lengths.min(),
        'max_length': label_lengths.max()
    }

    # Most common terms across all labels
    all_terms = []
    for label in df_labeled['cluster_label'].unique():
        all_terms.extend(label.lower().split())

    term_counts = Counter(all_terms)
    analysis['common_terms'] = term_counts.most_common(10)

    # Cluster size vs label diversity
    cluster_sizes = df_labeled.groupby('cluster').size()
    unique_labels = df_labeled.groupby('cluster')['cluster_label'].first()
    analysis['size_label_corr'] = cluster_sizes.corr(pd.Series([len(label.split()) for label in unique_labels]))

    return analysis


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Label K-means clusters using TF-IDF')
    parser.add_argument('--clusters_path', default='data/processed/kmeans_clusters.csv',
                       help='Path to clustered data CSV')
    parser.add_argument('--output_path', default='data/processed/clusters_labeled.csv',
                       help='Path to save labeled data')
    parser.add_argument('--text_columns', nargs='+',
                       help='Text columns to use for TF-IDF (default: auto-detect)')
    parser.add_argument('--top_n_terms', type=int, default=10,
                       help='Number of top TF-IDF terms to extract per cluster')
    parser.add_argument('--label_max_terms', type=int, default=4,
                       help='Maximum terms to include in cluster labels')
    parser.add_argument('--language', choices=['mixed', 'chinese', 'english'], default='mixed',
                       help='Language setting for text processing')
    parser.add_argument('--max_features', type=int, default=1000,
                       help='Maximum features for TF-IDF vectorizer')
    parser.add_argument('--ngram_range', type=int, nargs=2, default=[1, 2],
                       help='N-gram range for TF-IDF')

    args = parser.parse_args()

    print("Starting cluster labeling with TF-IDF...")
    labeled_df, cluster_labels = label_clusters(
        clusters_path=args.clusters_path,
        output_path=args.output_path,
        text_columns=args.text_columns,
        top_n_terms=args.top_n_terms,
        label_max_terms=args.label_max_terms,
        language=args.language,
        max_features=args.max_features,
        ngram_range=tuple(args.ngram_range)
    )

    # Analyze results
    analysis = analyze_cluster_quality(labeled_df)
    print("\nLabel Analysis:")
    print(f"Average label length: {analysis['label_stats']['mean_length']:.1f} terms")
    print(f"Most common terms: {analysis['common_terms'][:5]}")

    print("\nCluster labeling completed!")